name: Create Release
run-name: Creating draft release for ${{ github.ref_name }}

on:
  push:
    tags:
      - 'release-*'

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mvn -B clean package
      - id: version
        run: echo "::set-output name=number::`echo "${{ github.ref_name }}" | sed 's/release-//'`"
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
          --draft \
          --generate-notes \
          --title 'WebLogic Image Tool ${{ steps.version.outputs.number }}' \
          installer/target/imagetool.zip
