# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
name: Sonar Scan

on:
  push:
    branches:
      - 'main'
      - 'develop*'

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 11
      - name: Sonar Scan
        run: |
          mvn -B sonar:sonar \
          -Dsonar.branch.name=main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
